<?php

namespace App\Supports\Helpers;

use Illuminate\Support\Facades\Config;

class Constant {

    public static function flagList() {
        return [
            1 => 'Active',
            0 => 'Inactive',
        ];
    }

    public static function flagText($val) {

        return (bool)$val ? 'Active' : 'Inactive';
    }

    public static function genderList() {
        return [
            'm' => 'Male',
            'f' => 'Female',
        ];
    }

    public static function genderTitle($title) {
        $data = [
            'm' => 'Male',
            'f' => 'Female',
        ];
        return $data[$title] ?? '-';
    }

    public static function martialStatus() {

        return [
            "single" => "Single",
            "married" => "Married",
            "divorced" => "Divorced",
            "separated" => "Separated",
            "widowed" => "Widowed",
        ];
    }

    public static function religionsList() {

        return [
            'ahmadiyya' => 'Ahmadiyya',
            'aladura' => 'Aladura',
            'amish' => 'Amish',
            'anglicanism' => 'Anglicanism',
            'asatru' => 'Asatru',
            'assemblies of god' => 'Assemblies of God',
            'atheism' => 'Atheism',
            'bahai faith' => 'Bahai Faith',
            'baptists' => 'Baptists',
            'bon' => 'Bon',
            'buddhism' => 'Buddhism',
            'candomble' => 'Candomble',
            'cao dai' => 'Cao Dai',
            'cathari' => 'Cathari',
            'catholicism' => 'Catholicism',
            'charismatic movement' => 'Charismatic movement',
            'chinese religion' => 'Chinese Religion',
            'christadelphians' => 'Christadelphians',
            'christian science' => 'Christian Science',
            'christianity' => 'Christianity',
            'church of god' => 'Church of God',
            'church of god in christ' => 'Church of God in Christ',
            'church of satan' => 'Church of Satan',
            'confucianism' => 'Confucianism',
            'conservative judaism' => 'Conservative Judaism',
            'deism' => 'Deism',
            'donatism' => 'Donatism',
            'dragon rouge' => 'Dragon Rouge',
            'druze' => 'Druze',
            'eastern orthodox church' => 'Eastern Orthodox Church',
            'eckankar' => 'Eckankar',
            'elca' => 'ELCA',
            'epicureanism' => 'Epicureanism',
            'evangelicalism' => 'Evangelicalism',
            'falun gong' => 'Falun Gong',
            'foursquare church' => 'Foursquare Church',
            'gnosticism' => 'Gnosticism',
            'greek religion' => 'Greek Religion',
            'hare krishna' => 'Hare Krishna',
            'hasidism' => 'Hasidism',
            'hellenic reconstructionism' => 'Hellenic Reconstructionism',
            'hinduism' => 'Hinduism',
            'illuminati' => 'Illuminati',
            'intelligent design' => 'Intelligent Design',
            'islam' => 'Islam',
            'jainism' => 'Jainism',
            'jehovah witnesses' => 'Jehovah Witnesses',
            'judaism' => 'Judaism',
            'kabbalah' => 'Kabbalah',
            'kemetic reconstructionism' => 'Kemetic Reconstructionism',
            'lutheranism' => 'Lutheranism',
            'mahayana buddhism' => 'Mahayana Buddhism',
            'mayan religion' => 'Mayan Religion',
            'methodism' => 'Methodism',
            'mithraism' => 'Mithraism',
            'mormonism' => 'Mormonism',
            'neopaganism' => 'Neopaganism',
            'new age' => 'New Age',
            'new thought' => 'New Thought',
            'nichiren' => 'Nichiren',
            'norse religion' => 'Norse Religion',
            'olmec religion' => 'Olmec Religion',
            'oneness pentecostalism' => 'Oneness Pentecostalism',
            'orthodox judaism' => 'Orthodox Judaism',
            'pentecostalism' => 'Pentecostalism',
            'presbyterianism' => 'Presbyterianism',
            'priory of sion' => 'Priory of Sion',
            'protestantism' => 'Protestantism',
            'pure land buddhism' => 'Pure Land Buddhism',
            'quakers' => 'Quakers',
            'rastafarianism' => 'Rastafarianism',
            'reform judaism' => 'Reform Judaism',
            'rinzai zen buddhism' => 'Rinzai Zen Buddhism',
            'roman religion' => 'Roman Religion',
            'satanism' => 'Satanism',
            'scientology' => 'Scientology',
            'seventh-day adventism' => 'Seventh-Day Adventism',
            'shaivism' => 'Shaivism',
            'shia islam' => 'Shia Islam',
            'shinto' => 'Shinto',
            'sikhism' => 'Sikhism',
            'soto zen buddhism' => 'Soto Zen Buddhism',
            'spiritualism' => 'Spiritualism',
            'stoicism' => 'Stoicism',
            'sufism' => 'Sufism',
            'sunni islam' => 'Sunni Islam',
            'taoism' => 'Taoism',
            'tendai buddhism' => 'Tendai Buddhism',
            'theravada buddhism' => 'Theravada Buddhism',
            'tibetan buddhism' => 'Tibetan Buddhism',
            'typhonian order' => 'Typhonian Order',
            'umbanda' => 'Umbanda',
            'unification church' => 'Unification Church',
            'unitarian universalism' => 'Unitarian Universalism',
            'vaishnavism' => 'Vaishnavism',
            'vajrayana buddhism' => 'Vajrayana Buddhism',
            'vedanta' => 'Vedanta',
            'vineyard churches' => 'Vineyard Churches',
            'voodoo' => 'Voodoo',
            'westboro baptist church' => 'Westboro Baptist Church',
            'wicca' => 'Wicca',
            'worldwide church of god' => 'Worldwide Church of God',
            'yezidi' => 'Yezidi',
            'zen' => 'Zen',
            'zionism' => 'Zionism',
            'zoroastrianism' => 'Zoroastrianism',
        ];
    }

    public static function bloodGroupList() {

        return [
            "a+" => "A+",
            "a-" => "A-",
            "b+" => "B+",
            "b-" => "B-",
            "o+" => "O+",
            "o-" => "O-",
            "ab+" => "AB+",
            "ab-" => "AB-",
        ];
    }

    public static function gradesList() {

        return [
            "a+" => "A+",
            "a" => "A",
            "a-" => "A−",
            "b+" => "B+",
            "b-" => "B−",
            "c+" => "C+",
            "c" => "C",
            "c-" => "C−",
            "d+" => "D+",
            "d" => "D",
            "d-" => "D−",
            "f" => "F",
        ];
    }

    public static function languageList() {

        return [
            'abkhazian' => 'Abkhazian',
            'afan oromoor oriya' => 'Afan/Oromoor/Oriya',
            'afar' => 'Afar',
            'afrikaans' => 'Afrikaans',
            'albanian' => 'Albanian',
            'amharic' => 'Amharic',
            'arabic' => 'Arabic',
            'armenian' => 'Armenian',
            'assamese' => 'Assamese',
            'aymara' => 'Aymara',
            'azerbaijani' => 'Azerbaijani',
            'bashkir' => 'Bashkir',
            'basque' => 'Basque',
            'belarusian' => 'Belarusian',
            'bengali bangla' => 'Bengali/Bangla',
            'bhutani' => 'Bhutani',
            'bihari' => 'Bihari',
            'bislama' => 'Bislama',
            'breton' => 'Breton',
            'bulgarian' => 'Bulgarian',
            'burmese' => 'Burmese',
            'cambodian' => 'Cambodian',
            'catalan' => 'Catalan',
            'chinese' => 'Chinese',
            'corsican' => 'Corsican',
            'croatian' => 'Croatian',
            'czech' => 'Czech',
            'danish' => 'Danish',
            'dutch' => 'Dutch',
            'english' => 'English',
            'esperanto' => 'Esperanto',
            'estonian' => 'Estonian',
            'faeroese' => 'Faeroese',
            'fiji' => 'Fiji',
            'finnish' => 'Finnish',
            'french' => 'French',
            'frisian' => 'Frisian',
            'galician' => 'Galician',
            'georgian' => 'Georgian',
            'german' => 'German',
            'greek' => 'Greek',
            'greenlandic' => 'Greenlandic',
            'guarani' => 'Guarani',
            'gujarati' => 'Gujarati',
            'hausa' => 'Hausa',
            'hebrew' => 'Hebrew',
            'hindi' => 'Hindi',
            'hungarian' => 'Hungarian',
            'icelandic' => 'Icelandic',
            'indonesian' => 'Indonesian',
            'interlingua' => 'Interlingua',
            'interlingue' => 'Interlingue',
            'inupiak' => 'Inupiak',
            'irish' => 'Irish',
            'italian' => 'Italian',
            'japanese' => 'Japanese',
            'javanese' => 'Javanese',
            'kannada' => 'Kannada',
            'kashmiri' => 'Kashmiri',
            'kazakh' => 'Kazakh',
            'kinyarwanda' => 'Kinyarwanda',
            'kirghiz' => 'Kirghiz',
            'kirundi' => 'Kirundi',
            'korean' => 'Korean',
            'kurdish' => 'Kurdish',
            'laothian' => 'Laothian',
            'latin' => 'Latin',
            'latvian lettish' => 'Latvian/Lettish',
            'lingala' => 'Lingala',
            'lithuanian' => 'Lithuanian',
            'macedonian' => 'Macedonian',
            'malagasy' => 'Malagasy',
            'malay' => 'Malay',
            'malayalam' => 'Malayalam',
            'maltese' => 'Maltese',
            'maori' => 'Maori',
            'marathi' => 'Marathi',
            'moldavian' => 'Moldavian',
            'mongolian' => 'Mongolian',
            'nauru' => 'Nauru',
            'nepali' => 'Nepali',
            'norwegian' => 'Norwegian',
            'occitan' => 'Occitan',
            'pashto pushto' => 'Pashto/Pushto',
            'persian' => 'Persian',
            'polish' => 'Polish',
            'portuguese' => 'Portuguese',
            'punjabi' => 'Punjabi',
            'quechua' => 'Quechua',
            'rhaeto romance' => 'Rhaeto-Romance',
            'romanian' => 'Romanian',
            'russian' => 'Russian',
            'samoan' => 'Samoan',
            'sangro' => 'Sangro',
            'sanskrit' => 'Sanskrit',
            'scots gaelic' => 'Scots/Gaelic',
            'serbian' => 'Serbian',
            'serbo croatian' => 'Serbo-Croatian',
            'sesotho' => 'Sesotho',
            'setswana' => 'Setswana',
            'shona' => 'Shona',
            'sindhi' => 'Sindhi',
            'singhalese' => 'Singhalese',
            'siswati' => 'Siswati',
            'slovak' => 'Slovak',
            'slovenian' => 'Slovenian',
            'somali' => 'Somali',
            'spanish' => 'Spanish',
            'sundanese' => 'Sundanese',
            'swahili' => 'Swahili',
            'swedish' => 'Swedish',
            'tagalog' => 'Tagalog',
            'tajik' => 'Tajik',
            'tamil' => 'Tamil',
            'tatar' => 'Tatar',
            'telugu' => 'Telugu',
            'thai' => 'Thai',
            'tibetan' => 'Tibetan',
            'tigrinya' => 'Tigrinya',
            'tonga' => 'Tonga',
            'tsonga' => 'Tsonga',
            'turkish' => 'Turkish',
            'turkmen' => 'Turkmen',
            'twi' => 'Twi',
            'ukrainian' => 'Ukrainian',
            'urdu' => 'Urdu',
            'uzbek' => 'Uzbek',
            'vietnamese' => 'Vietnamese',
            'volapuk' => 'Volapuk',
            'welsh' => 'Welsh',
            'wolof' => 'Wolof',
            'xhosa' => 'Xhosa',
            'yiddish' => 'Yiddish',
            'yoruba' => 'Yoruba',
            'zulu' => 'Zulu',
        ];
    }

    public static function currencyList() {

        return [
            'aed' => 'AED',
            'afn' => 'AFN',
            'all' => 'ALL',
            'amd' => 'AMD',
            'aoa' => 'AOA',
            'ars' => 'ARS',
            'aud' => 'AUD',
            'azn' => 'AZN',
            'bam' => 'BAM',
            'bbd' => 'BBD',
            'bdt' => 'BDT',
            'bgn' => 'BGN',
            'bhd' => 'BHD',
            'bif' => 'BIF',
            'bnd' => 'BND',
            'bob' => 'BOB',
            'brl' => 'BRL',
            'bsd' => 'BSD',
            'btn' => 'BTN',
            'bwp' => 'BWP',
            'byn' => 'BYN',
            'bzd' => 'BZD',
            'cad' => 'CAD',
            'cdf' => 'CDF',
            'chf' => 'CHF',
            'clp' => 'CLP',
            'cny' => 'CNY',
            'cop' => 'COP',
            'crc' => 'CRC',
            'cup' => 'CUP',
            'cve' => 'CVE',
            'czk' => 'CZK',
            'djf' => 'DJF',
            'dkk' => 'DKK',
            'dop' => 'DOP',
            'dzd' => 'DZD',
            'egp' => 'EGP',
            'ern' => 'ERN',
            'etb' => 'ETB',
            'eur' => 'EUR',
            'fjd' => 'FJD',
            'gbp' => 'GBP',
            'gel' => 'GEL',
            'ghs' => 'GHS',
            'gmd' => 'GMD',
            'gnf' => 'GNF',
            'gtq' => 'GTQ',
            'gyd' => 'GYD',
            'hnl' => 'HNL',
            'hrk' => 'HRK',
            'htg' => 'HTG',
            'huf' => 'HUF',
            'idr' => 'IDR',
            'ils' => 'ILS',
            'inr' => 'INR',
            'iqd' => 'IQD',
            'irr' => 'IRR',
            'isk' => 'ISK',
            'jmd' => 'JMD',
            'jod' => 'JOD',
            'jpy' => 'JPY',
            'kes' => 'KES',
            'kgs' => 'KGS',
            'khr' => 'KHR',
            'kmf' => 'KMF',
            'kpw' => 'KPW',
            'krw' => 'KRW',
            'kwd' => 'KWD',
            'kzt' => 'KZT',
            'lak' => 'LAK',
            'lbp' => 'LBP',
            'lkr' => 'LKR',
            'lrd' => 'LRD',
            'lsl' => 'LSL',
            'lyd' => 'LYD',
            'mad' => 'MAD',
            'mdl' => 'MDL',
            'mga' => 'MGA',
            'mkd' => 'MKD',
            'mmk' => 'MMK',
            'mnt' => 'MNT',
            'mro' => 'MRO',
            'mur' => 'MUR',
            'mvr' => 'MVR',
            'mwk' => 'MWK',
            'mxn' => 'MXN',
            'myr' => 'MYR',
            'mzn' => 'MZN',
            'nad' => 'NAD',
            'ngn' => 'NGN',
            'nio' => 'NIO',
            'nok' => 'NOK',
            'npr' => 'NPR',
            'nzd' => 'NZD',
            'omr' => 'OMR',
            'pab' => 'PAB',
            'pen' => 'PEN',
            'pgk' => 'PGK',
            'php' => 'PHP',
            'pkr' => 'PKR',
            'pln' => 'PLN',
            'pyg' => 'PYG',
            'qar' => 'QAR',
            'ron' => 'RON',
            'rsd' => 'RSD',
            'rub' => 'RUB',
            'rwf' => 'RWF',
            'sar' => 'SAR',
            'sbd' => 'SBD',
            'scr' => 'SCR',
            'sdg' => 'SDG',
            'sek' => 'SEK',
            'sgd' => 'SGD',
            'sll' => 'SLL',
            'sos' => 'SOS',
            'srd' => 'SRD',
            'ssp' => 'SSP',
            'std' => 'STD',
            'syp' => 'SYP',
            'szl' => 'SZL',
            'thb' => 'THB',
            'tjs' => 'TJS',
            'tmt' => 'TMT',
            'tnd' => 'TND',
            'top' => 'TOP',
            'try' => 'TRY',
            'ttd' => 'TTD',
            'twd' => 'TWD',
            'tzs' => 'TZS',
            'uah' => 'UAH',
            'ugx' => 'UGX',
            'usd' => 'USD',
            'uyu' => 'UYU',
            'uzs' => 'UZS',
            'vef' => 'VEF',
            'vnd' => 'VND',
            'vuv' => 'VUV',
            'wst' => 'WST',
            'xaf' => 'XAF',
            'xcd' => 'XCD',
            'xof' => 'XOF',
            'yer' => 'YER',
            'zar' => 'ZAR',
            'zmw' => 'ZMW',
        ];
    }

    public static function LanguageAbilities() {

        return [
            "beginner" => "Beginner",
            "moderate" => "Moderate",
            "expert" => "Expert",
            "advance" => "Advance",
        ];
    }

    public static function dataTypeList() {
        return [
            'text' => 'Text',
            'datetime' => 'Date Time',
        ];
    }

    public static function adminImg($img) {
        if ($img == '' || $img == null) {
            return asset(UPLOADS_APP . DIRECTORY_SEPARATOR . "user.png");
        }
        return asset(UPLOADS_ADMIN . DIRECTORY_SEPARATOR . $img);
    }

    public static function userImg($img) {
        if ($img == '' || $img == null) {
            return asset(UPLOADS_APP . DIRECTORY_SEPARATOR . "user.png");
        }
        return asset(UPLOADS_USER . DIRECTORY_SEPARATOR . $img);
    }

    public static function loadImg($img, $path) {
        if ($img == '' || $img == null) {
            return asset(UPLOADS_APP . DIRECTORY_SEPARATOR . "placeholder-blue.jpg");
        }
        return asset("uploads/{$path}/" . $img);
    }




    public static function getCountriesList() {

        return [
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarctica",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegowina",
            "Botswana",
            "Bouvet Island",
            "Brazil",
            "British Indian Ocean Territory",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Congo",
            "Congo, the Democratic Republic of the",
            "Cook Islands",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia (Hrvatska)",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Falkland Islands (Malvinas)",
            "Faroe Islands",
            "Fiji",
            "Finland",
            "France",
            "France Metropolitan",
            "French Guiana",
            "French Polynesia",
            "French Southern Territories",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Heard and Mc Donald Islands",
            "Holy See (Vatican City State)",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran (Islamic Republic of)",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea, Democratic People's Republic of",
            "Korea, Republic of",
            "Kuwait",
            "Kyrgyzstan",
            "Lao, People's Democratic Republic",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libyan Arab Jamahiriya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macau",
            "Macedonia, The Former Yugoslav Republic of",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia, Federated States of",
            "Moldova, Republic of",
            "Monaco",
            "Mongolia",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "Netherlands Antilles",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Pitcairn",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Reunion",
            "Romania",
            "Russian Federation",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia (Slovak Republic)",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Georgia and the South Sandwich Islands",
            "Spain",
            "Sri Lanka",
            "St. Helena",
            "St. Pierre and Miquelon",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen Islands",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syrian Arab Republic",
            "Taiwan, Province of China",
            "Tajikistan",
            "Tanzania, United Republic of",
            "Thailand",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "United States Minor Outlying Islands",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Vietnam",
            "Virgin Islands (British)",
            "Virgin Islands (U.S.)",
            "Wallis and Futuna Islands",
            "Western Sahara",
            "Yemen",
            "Yugoslavia",
            "Zambia",
            "Zimbabwe",
        ];
    }// getCountriesList end

    public static function getCitiesList() {

        return [
            'abbottabad_district' => 'Abbottabad District',
            'abdul_hakim' => 'Abdul Hakim',
            'ahmadpur_east' => 'Ahmadpur East',
            'ahmadpur_sial' => 'Ahmadpur Sial',
            'alipur' => 'Alipur',
            'alipur_chatha' => 'Alipur Chatha',
            'amangarh' => 'Amangarh',
            'arifwala' => 'Arifwala',
            'attock' => 'Attock',
            'awaran_district' => 'Awaran District',
            'badah' => 'Badah',
            'badin' => 'Badin',
            'bahawalnagar' => 'Bahawalnagar',
            'bahawalpur' => 'Bahawalpur',
            'bajaur_agency' => 'Bajaur Agency',
            'bannu_district' => 'Bannu District',
            'bannu_tribal_area' => 'Bannu Tribal Area',
            'barkhan_district' => 'Barkhan District',
            'basirpur' => 'Basirpur',
            'bat_khela' => 'Bat Khela',
            'battagram_district' => 'Battagram District',
            'bhakkar' => 'Bhakkar',
            'bhalwal' => 'Bhalwal',
            'bhera' => 'Bhera',
            'bolan_district' => 'Bolan District',
            'buner_district' => 'Buner District',
            'burewala' => 'Burewala',
            'chagai_district' => 'Chagai District',
            'chak_jhumra' => 'Chak Jhumra',
            'chakwal' => 'Chakwal',
            'charsadda_district' => 'Charsadda District',
            'chawinda' => 'Chawinda',
            'chawkay' => 'Chawkay',
            'chenab_nagar' => 'Chenab Nagar',
            'chichawatni' => 'Chichawatni',
            'chiniot' => 'Chiniot',
            'chishtian' => 'Chishtian',
            'chitral_district' => 'Chitral District',
            'chowk_azam' => 'Chowk Azam',
            'chowk_sarwar' => 'Chowk Sarwar',
            'chunian' => 'Chunian',
            'dadu' => 'Dadu',
            'daharki' => 'Daharki',
            'dalbandin_nok_kundi' => 'Dalbandin Nok Kundi',
            'darya_khan' => 'Darya Khan',
            'daska' => 'Daska',
            'daud_khel' => 'Daud Khel',
            'dera_bugti_district' => 'Dera Bugti District',
            'dera_ghazi_khan' => 'Dera Ghazi Khan',
            'dera_ismail_khan_district' => 'Dera Ismail Khan District',
            'dera_ismail_khan_tribal_area' => 'Dera Ismail Khan Tribal Area',
            'digri' => 'Digri',
            'dijkot' => 'Dijkot',
            'dina' => 'Dina',
            'dinga' => 'Dinga',
            'dipalpur' => 'Dipalpur',
            'dunga_bunga' => 'Dunga Bunga',
            'dunyapur' => 'Dunyapur',
            'faisalabad' => 'Faisalabad',
            'faqirwali' => 'Faqirwali',
            'faruqabad' => 'Faruqabad',
            'fatehjang' => 'Fatehjang',
            'fazilpur' => 'Fazilpur',
            'firozwala' => 'Firozwala',
            'fort_abbas' => 'Fort Abbas',
            'gambat' => 'Gambat',
            'garh_maharaja' => 'Garh Maharaja',
            'ghakhar' => 'Ghakhar',
            'ghauspur' => 'Ghauspur',
            'ghotki' => 'Ghotki',
            'gojra' => 'Gojra',
            'guddu' => 'Guddu',
            'gujar_khan' => 'Gujar Khan',
            'gujranwala' => 'Gujranwala',
            'gujranwala_cantonment' => 'Gujranwala Cantonment',
            'gujrat' => 'Gujrat',
            'gwadar_district' => 'Gwadar District',
            'hadali' => 'Hadali',
            'hafizabad' => 'Hafizabad',
            'hala' => 'Hala',
            'hangu_district' => 'Hangu District',
            'haripur_district' => 'Haripur District',
            'harnai' => 'Harnai',
            'harunabad' => 'Harunabad',
            'hasan_abdal' => 'Hasan Abdal',
            'hasilpur' => 'Hasilpur',
            'haveli_lakha' => 'Haveli Lakha',
            'hazara_division' => 'Hazara Division',
            'hazro' => 'Hazro',
            'hujra_shah_muqim' => 'Hujra Shah Muqim',
            'hyderabad' => 'Hyderabad',
            'jacobabad' => 'Jacobabad',
            'jafarabad_district' => 'Jafarabad District',
            'jalalpur_bhattian' => 'Jalalpur Bhattian',
            'jalalpur_jattan' => 'Jalalpur Jattan',
            'jalalpur_pirwala' => 'Jalalpur Pirwala',
            'jamke_chima' => 'Jamke Chima',
            'jampur' => 'Jampur',
            'jaranwala' => 'Jaranwala',
            'jatoi' => 'Jatoi',
            'jauharabad' => 'Jauharabad',
            'jehanian' => 'Jehanian',
            'jhal_magsi_district' => 'Jhal Magsi District',
            'jhang' => 'Jhang',
            'jhawarian' => 'Jhawarian',
            'jhelum' => 'Jhelum',
            'jhudo' => 'Jhudo',
            'kabirwala' => 'Kabirwala',
            'kachhi_district' => 'Kachhi District',
            'kahror_pakka' => 'Kahror Pakka',
            'kalat_district' => 'Kalat District',
            'kalat_division' => 'Kalat Division',
            'kalur_kot' => 'Kalur Kot',
            'kamalia' => 'Kamalia',
            'kambar' => 'Kambar',
            'kamir' => 'Kamir',
            'kamoki' => 'Kamoki',
            'kamra_cantonment' => 'Kamra Cantonment',
            'kandhkot' => 'Kandhkot',
            'kandiaro' => 'Kandiaro',
            'karachi' => 'Karachi',
            'karak_district' => 'Karak District',
            'karor_lal_esan' => 'Karor Lal Esan',
            'kashmor' => 'Kashmor',
            'kasur' => 'Kasur',
            'kech_district' => 'Kech District',
            'khairpur' => 'Khairpur',
            'khairpur_tamewali' => 'Khairpur Tamewali',
            'khanewal' => 'Khanewal',
            'khanpur' => 'Khanpur',
            'khanqah_dogran' => 'Khanqah Dogran',
            'kharan_district' => 'Kharan District',
            'kharian' => 'Kharian',
            'khaīrpur' => 'Khaīrpur',
            'khewra' => 'Khewra',
            'khipro' => 'Khipro',
            'khudian' => 'Khudian',
            'khurianwala' => 'Khurianwala',
            'khushab' => 'Khushab',
            'khuzdar_district' => 'Khuzdar District',
            'khyber_agency' => 'Khyber Agency',
            'kohat_district' => 'Kohat District',
            'kohat_tribal_area' => 'Kohat Tribal Area',
            'kohistan_district' => 'Kohistan District',
            'kohlu_district' => 'Kohlu District',
            'kot_abdul_malik' => 'Kot Abdul Malik',
            'kot_addu' => 'Kot Addu',
            'kot_diji' => 'Kot Diji',
            'kot_mumin' => 'Kot Mumin',
            'kot_radha_kishan' => 'Kot Radha Kishan',
            'kot_samaba' => 'Kot Samaba',
            'kotri' => 'Kotri',
            'kundian' => 'Kundian',
            'kunjah' => 'Kunjah',
            'kunri' => 'Kunri',
            'kurram_agency' => 'Kurram Agency',
            'lahore' => 'Lahore',
            'lakki_marwat_district' => 'Lakki Marwat District',
            'lakki_marwat_tribal_area' => 'Lakki Marwat Tribal Area',
            'lala_musa' => 'Lala Musa',
            'lalian' => 'Lalian',
            'larkana' => 'Larkana',
            'lasbela_district' => 'Lasbela District',
            'layyah' => 'Layyah',
            'liaquatabad' => 'Liaquatabad',
            'liaquatpur' => 'Liaquatpur',
            'lodhran' => 'Lodhran',
            'loralai_district' => 'Loralai District',
            'lower_dir_district' => 'Lower Dir District',
            'ludhewala_warraich' => 'Ludhewala Warraich',
            'mailsi' => 'Mailsi',
            'makran_division' => 'Makran Division',
            'malakand_division' => 'Malakand Division',
            'malakand_protected_area' => 'Malakand Protected Area',
            'malakwal' => 'Malakwal',
            'mamu_kanjan' => 'Mamu Kanjan',
            'mananwala_jodh_singh' => 'Mananwala Jodh Singh',
            'mandi_bahauddin' => 'Mandi Bahauddin',
            'mansehra_district' => 'Mansehra District',
            'mardan_district' => 'Mardan District',
            'mastung_district' => 'Mastung District',
            'matli' => 'Matli',
            'mehar' => 'Mehar',
            'mehrabpur' => 'Mehrabpur',
            'mian_channu' => 'Mian Channu',
            'mianwali' => 'Mianwali',
            'minchinabad' => 'Minchinabad',
            'mitha_tiwana' => 'Mitha Tiwana',
            'mohmand_agency' => 'Mohmand Agency',
            'moro' => 'Moro',
            'multan' => 'Multan',
            'muridke' => 'Muridke',
            'murree' => 'Murree',
            'musa_khel_district' => 'Musa Khel District',
            'mustafabad' => 'Mustafabad',
            'muzaffargarh' => 'Muzaffargarh',
            'mīrpur_khas' => 'Mīrpur Khas',
            'mīrpur_mathelo' => 'Mīrpur Mathelo',
            'nankana_sahib' => 'Nankana Sahib',
            'narang' => 'Narang',
            'narowal' => 'Narowal',
            'nasirabad_district' => 'Nasirabad District',
            'nasīrabad' => 'Nasīrabad',
            'naudero' => 'Naudero',
            'nawabshah' => 'Nawabshah',
            'north_waziristan_agency' => 'North Waziristan Agency',
            'nowshera_district' => 'Nowshera District',
            'nowshera_virkan' => 'Nowshera Virkan',
            'nushki_district' => 'Nushki District',
            'okara' => 'Okara',
            'okara_cantonment' => 'Okara Cantonment',
            'orakzai_agency' => 'Orakzai Agency',
            'pakpattan' => 'Pakpattan',
            'panjgur_district' => 'Panjgur District',
            'pano_aqil' => 'Pano Aqil',
            'pano_aqil_cantonment' => 'Pano Aqil Cantonment',
            'pasrur' => 'Pasrur',
            'pattoki' => 'Pattoki',
            'peshawar_district' => 'Peshawar District',
            'peshawar_division' => 'Peshawar Division',
            'peshawar_tribal_area' => 'Peshawar Tribal Area',
            'phalia' => 'Phalia',
            'phulnagar' => 'Phulnagar',
            'pindi_bhattian' => 'Pindi Bhattian',
            'pindi_gheb' => 'Pindi Gheb',
            'pir_mahal' => 'Pir Mahal',
            'pishin_district' => 'Pishin District',
            'pīrjo_goth' => 'Pīrjo Goth',
            'qila_abdullah_district' => 'Qila Abdullah District',
            'qila_didar_singh' => 'Qila Didar Singh',
            'qila_saifullah_district' => 'Qila Saifullah District',
            'quetta_district' => 'Quetta District',
            'quetta_division' => 'Quetta Division',
            'rahimyar_khan' => 'Rahimyar Khan',
            'raja_jang' => 'Raja Jang',
            'rajanpur' => 'Rajanpur',
            'ratodero' => 'Ratodero',
            'rawalpindi' => 'Rawalpindi',
            'renala_khurd' => 'Renala Khurd',
            'rohri' => 'Rohri',
            'sadiqabad' => 'Sadiqabad',
            'safdarabad' => 'Safdarabad',
            'sahiwal' => 'Sahiwal',
            'sakrand' => 'Sakrand',
            'samasata' => 'Samasata',
            'sambrial' => 'Sambrial',
            'samundri' => 'Samundri',
            'sanghar' => 'Sanghar',
            'sangla_hill' => 'Sangla Hill',
            'sarai_alamgir' => 'Sarai Alamgir',
            'sargodha' => 'Sargodha',
            'sehwan' => 'Sehwan',
            'setharja' => 'Setharja',
            'shahdadkot' => 'Shahdadkot',
            'shahdadpur' => 'Shahdadpur',
            'shahkot' => 'Shahkot',
            'shakargarh' => 'Shakargarh',
            'shangla_district' => 'Shangla District',
            'sharqpur' => 'Sharqpur',
            'sheikhupura' => 'Sheikhupura',
            'shikarpur' => 'Shikarpur',
            'shirani' => 'Shirani',
            'shorkot' => 'Shorkot',
            'shujaabad' => 'Shujaabad',
            'sialkot' => 'Sialkot',
            'sibi_district' => 'Sibi District',
            'sillanwali' => 'Sillanwali',
            'south_waziristan_agency' => 'South Waziristan Agency',
            'sujawal' => 'Sujawal',
            'sukheke' => 'Sukheke',
            'sukkur' => 'Sukkur',
            'swabi_district' => 'Swabi District',
            'swat_district' => 'Swat District',
            'sīta_road' => 'Sīta Road',
            'takht_bhati' => 'Takht Bhati',
            'talagang' => 'Talagang',
            'tandlianwala' => 'Tandlianwala',
            'tando_adam' => 'Tando Adam',
            'tando_allahyar' => 'Tando Allahyar',
            'tando_jam' => 'Tando Jam',
            'tando_muhammad_khan' => 'Tando Muhammad Khan',
            'tangi' => 'Tangi',
            'tank' => 'Tank',
            'tank_district' => 'Tank District',
            'tank_tribal_area' => 'Tank Tribal Area',
            'taunsa' => 'Taunsa',
            'taxila' => 'Taxila',
            'thall' => 'Thall',
            'thatta' => 'Thatta',
            'thul' => 'Thul',
            'timargara' => 'Timargara',
            'toba_tek_singh' => 'Toba Tek Singh',
            'topi' => 'Topi',
            'tor_ghar' => 'Tor Ghar',
            'tordher' => 'Tordher',
            'trinda_sawai_khan' => 'Trinda Sawai Khan',
            'tulamba' => 'Tulamba',
            'ubauro' => 'Ubauro',
            'uch' => 'Uch',
            'umerkot' => 'Umerkot',
            'upper_dir_district' => 'Upper Dir District',
            'utmanzai' => 'Utmanzai',
            'vehari' => 'Vehari',
            'wah_cantonment' => 'Wah Cantonment',
            'washuk_district' => 'Washuk District',
            'wazirabad' => 'Wazirabad',
            'yazman' => 'Yazman',
            'zahir_pir' => 'Zahir Pir',
            'zhob_district' => 'Zhob District',
            'ziarat_district' => 'Ziarat District',
        ];
    }


}